version: "3.8"

services:
  sensor:
    build:
      context: ./sensor
    container_name: sensor
    restart: always

  receiver:
    build:
      context: ./receiver
    container_name: receiver
    depends_on:
      - sensor
    restart: always

  