version: "3.8"

services:
  sensor:
    build: ./sensor
    container_name: sensor
    restart: always

  gateway:
    build: ./gateway
    container_name: gateway
    depends_on:
      - sensor
    restart: always

  cloud_connector:
    build: ./cloud_connector
    container_name: cloud_connector
    restart: always
    ports:
      - "5000:5000"

  visualization:
    build: ./visualization
    container_name: visualization
    ports:
      - "5001:80"
    restart: always
